[build]
  command = "pnpm install && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "10.15.1"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Instalar pnpm globalmente en Netlify
[[build.processing]]
  skip_processing = false

[build.processing.before]
  commands = ["npm install -g pnpm@10.15.1"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para archivos JavaScript
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para archivos CSS
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para archivos de assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
